src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=licence::class, mappedBy="category")
     */
    private $licence;

    public function __construct()
    {
        $this->licence = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|licence[]
     */
    public function getLicence(): Collection
    {
        return $this->licence;
    }

    public function addLicence(licence $licence): self
    {
        if (!$this->licence->contains($licence)) {
            $this->licence[] = $licence;
            $licence->setCategory($this);
        }

        return $this;
    }

    public function removeLicence(licence $licence): self
    {
        if ($this->licence->removeElement($licence)) {
            // set the owning side to null (unless already changed)
            if ($licence->getCategory() === $this) {
                $licence->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Inventory.php
<?php

namespace App\Entity;

use App\Repository\InventoryRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=InventoryRepository::class)

 */
class Inventory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 5,
     *      max = 50,
     *      minMessage = "This field must be at least {{ limit }} characters long",
     *      maxMessage = "This field cannot be longer than {{ limit }} characters",
       
     * )
     */
    private $Equipment;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 3,
     *      max = 50,
     *      minMessage = " This field must be at least {{ limit }} characters long",
     *      maxMessage = "This fieldcannot be longer than {{ limit }} characters",
       
     * )
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Locaation;

    /**
     * @ORM\Column(type="text", nullable=true)
     
     */
    private $Notes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $OperatingSystem;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\Length(
     *      min = 3,
     *      max = 50,
     *      minMessage = " This field must be at least {{ limit }} characters long",
     *      maxMessage = "This fieldcannot be longer than {{ limit }} characters",
       
     * )
     */
    private $State;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\Length(
     *      min = 3,
     *      max = 50,
     *      minMessage = " This field must be at least 3 characters long",
     *      maxMessage = "This fieldcannot be longer than 50 characters",
       
     * )
     */
    private $Brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *  * @Assert\Length(
     *      min = 8,
     *      max = 50,
     *      minMessage = " This field must be at least 8 characters long",
     *      maxMessage = "This fieldcannot be longer than 50 characters",
       
     * )
     */
    private $Model;

    /**
     * @ORM\Column(type="date", length=255, nullable=true)
     */
    private $PurchaseDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Supplier;

    /**
     * @ORM\Column(type="date", length=255, nullable=true)
     */
    private $LastScan;

    /**
     * @ORM\Column(type="date", length=255, nullable=true)
     */
    private $LastMaintenance;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $CreatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEquipment(): ?string
    {
        return $this->Equipment;
    }

    public function setEquipment(string $Equipment): self
    {
        $this->Equipment = $Equipment;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getLocaation(): ?string
    {
        return $this->Locaation;
    }

    public function setLocaation(string $Locaation): self
    {
        $this->Locaation = $Locaation;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->Notes;
    }

    public function setNotes(?string $Notes): self
    {
        $this->Notes = $Notes;

        return $this;
    }

    public function getOperatingSystem(): ?string
    {
        return $this->OperatingSystem;
    }

    public function setOperatingSystem(?string $OperatingSystem): self
    {
        $this->OperatingSystem = $OperatingSystem;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->State;
    }

    public function setState(string $State): self
    {
        $this->State = $State;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->Model;
    }

    public function setModel(?string $Model): self
    {
        $this->Model = $Model;

        return $this;
    }

    public function getPurchaseDate(): ?\DateTimeInterface
    {
        return $this->PurchaseDate;
    }

    public function setPurchaseDate(\DateTimeInterface $PurchaseDate): self
    {
        $this->PurchaseDate = $PurchaseDate;

        return $this;
    }

    public function getSupplier(): ?string
    {
        return $this->Supplier;
    }

    public function setSupplier(?string $Supplier): self
    {
        $this->Supplier = $Supplier;

        return $this;
    }

    public function getLastScan(): ?\DateTimeInterface
    {
        return $this->LastScan;
    }

    public function setLastScan(\DateTimeInterface $LastScan): self
    {
        $this->LastScan = $LastScan;

        return $this;
    }

    public function getLastMaintenance(): ?\DateTimeInterface
    {
        return $this->LastMaintenance;
    }

    public function setLastMaintenance(\DateTimeInterface $LastMaintenance): self
    {
        $this->LastMaintenance = $LastMaintenance;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }
}

src/Entity/Licence.php
<?php

namespace App\Entity;

use App\Repository\LicenceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LicenceRepository::class)
 */
class Licence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Product_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Supplier;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Compilance_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $User;

    /**
     * @ORM\Column(type="date")
     */
    private $Purchase_date;

    /**
     * @ORM\Column(type="date")
     */
    private $expiration_date;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $CreatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="licence")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->Product_name;
    }

    public function setProductName(string $Product_name): self
    {
        $this->Product_name = $Product_name;

        return $this;
    }

    public function getSupplier(): ?string
    {
        return $this->Supplier;
    }

    public function setSupplier(?string $Supplier): self
    {
        $this->Supplier = $Supplier;

        return $this;
    }

   
    public function getCompilanceType(): ?string
    {
        return $this->Compilance_type;
    }

    public function setCompilanceType(?string $Compilance_type): self
    {
        $this->Compilance_type = $Compilance_type;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(?string $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getPurchaseDate(): ?\DateTimeInterface
    {
        return $this->Purchase_date;
    }

    public function setPurchaseDate(\DateTimeInterface $Purchase_date): self
    {
        $this->Purchase_date = $Purchase_date;

        return $this;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(\DateTimeInterface $expiration_date): self
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

templates/company/Inventory.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<style>
a{color:black;}
th,h2{color:#485785}
.b{padding-left:400px;}
</style><section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
    
    <h2>These are your inventory items :</h2>
    <a href="{{path("inventory_new")}}" class="btn btn-outline-info btn-lg float-right" ><i class="fas fa-user-plus"></i>Add Equipement to your inventory</a>
<br><br><br>{{form_start(form)}}

    <div class="form-row align-items-end">
    <div class="col-sm">
      {{form_row(form.location,{'attr':{'placeholder':'Location'}})}}
    </div>
    <div class="col-sm">
      {{form_row(form.operatingsystem)}}
    </div>
    <div class="col-sm">
      {{form_row(form.state)}}
    </div>
    <div class="col-sm">
      {{form_row(form.brand)}}
    </div>
    <div class="form-group">
    <button class=" btn search">
                        <i class="fa fa-search"></i></button>
    
     {{form_end(form)}}
     
    
    <a class="btn search" href='/company/inventory'>
                        <i class="fa fa-redo"></i></button></a></div>
 </div>
 <div class="panel panel-default">
    <div class="panel-heading">
     Inventory
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr><th scope="col">Equipment</th>
      <th scope="col">User</th>
      <th scope="col">Location</th>
      
       <th scope="col">OperatingSystem</th>
      <th scope="col">State</th>
       <th scope="col">Brand</th>
      <th scope="col">LastScan</th>
      <th scope="col">LastMaintenance</th>
         <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for inventory in inventorys %}
    <tr>
      <td scope="row" >{{inventory.Equipment}}</th>
      <td>{{inventory.User}}</td>
      <td>{{inventory.Locaation}}</td>
      
       <td>{{inventory.OperatingSystem}}</td>
      <td>{{inventory.State}}</td>
      
       <td>{{inventory.Brand}}</td>
      <td>{{inventory.LastScan|date("m/d/Y")}}</td>
      <td>{{inventory.LastMaintenance|date("m/d/Y")}}</td>
       <td> <a href="{{path('inventory_show',{'id':inventory.id})}}"><i class="far fa-eye"></i></a>
          
           <a href="{{path('inventory_edit',{'id':inventory.id})}}" ><i class="fas fa-edit"></i> </a>
           <a href="{{path('inventory_delete',{'id':inventory.id})}}" onclick="return confirm('Are you sure you want to delete this item?');" data-id=""{{inventory.id}}><i class="fas fa-trash delete-inventory"></i> </a>
          </td>
    </tr>
   {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
</section></section>
     <div class="container">
  
<div class="navigation b">
    {{ knp_pagination_render(inventorys) }}
</div>



</div>
  
{% endblock %}
{% block javascripts %}
<script src="{{ asset('js/main.js') }}"></script>
<script>
function myFunction() {
  alert("Equipment is Now being deleted");
}
</script>

{% endblock %}

templates/company/ResetPassword.html.twig
{% extends 'base.html.twig' %}
{% block body %}
      <style>
      .blue{
        float:right;
     
          margin-bottom:10px;
          margin-left:400px;
      }
        .space{
        float:right;
      
          margin-left:150px;
      }
      .a{
          float:right;
      }
      h2{color:#485785}</style>
     <section id="main-content">
	<section class="wrapper">
  <div class="table-agile-info">
 
<h2>Reset Password</h2>
{{form_start(form)}}


<br><br><br>
{{form_end(form)}}
<form method="post">
<label for="pwd">Password:</label>
<input type="password" id="pwd" name="pass1">
<label for="pwd">Password 2:</label>
<input type="password" id="pass2" name="pass2">
<button type="submit">oui</button>
</form><br><br><br><br></div><br><br><br><br><br><br><br><br>
</section>
</section>
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
a{color:black;}
i,strong,p{color:white;}
.i{color:black;}
.x{background-color:#FC3158;}

.y{background-color:#53d769;}

.z{background-color:#147EFB;}

.e{background-color:#2A2727;}
th,h2{color:#485785}
.b{padding-left:400px;}
</style>
    
{% if  is_granted('ROLE_ADMIN') %}
<section id="main-content">
	<section class="wrapper">
  <div class="agil-info-calendar">
		<!-- calendar -->
		<div class="col-md-6 agile-calendar">
			<div class="calendar-widget">
                <div class="panel-heading ui-sortable-handle">
					<span class="panel-icon">
                      <i class="fas fa-calendar" style="color:black;"></i>
                    </span>
                    <span class="panel-title"> Calendar </span>
                </div>
				<!-- grids -->
					<div class="agile-calendar-grid">
						<div class="page">
							
							<div class="w3l-calendar-left">
								<div class="calendar-heading">
									
								</div>
								<div class="monthly" id="mycalendar"></div>
							</div>
							
							<div class="clearfix"> </div>
						</div>
					</div>
			</div>
		</div><div class="col-md-6 w3agile-notifications">
			<div class="notifications">
				<!--notification start--><div class="container">
        <h3>Info</h3>
  <div class="row">
    <div class="col">
                        <i class="fa fa-history i"></i>
   Transactions:{{Transactions|length}}<br><br>
   
                        <i class="fa fa-boxes i"></i>
   Inventory Items:{{Inventorys|length}}
    </div>
    <div class="col">
                        <i class="fa fa-box-open i"></i>
     Products:{{Products|length}}
     <br><br>
   
                        <i class="fa fa-users i"></i>
   Users:{{User|length}}
    </div>
    <div class="col">
      One of three columns
    </div>
  </div>
</div><br>
					<header class="panel-heading">
					Recent Reports
					</header>{% for email in emails %}
					<div class="notify-w3ls">
						<div class="alert alert-info clearfix">
							<span class="alert-icon"><i class="fa fa-envelope"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="{{path('email_show',{'id':email.id})}}">{{email.user.username}}</a></span> sent you a report </li>
									<li class="pull-right notification-time">{{email.CreatedAt|date("m/d/Y") }}</li>
								</ul>
								<p>
								{{email.content}}
								</p>
							</div>
						</div>
					{% endfor %}
				
				<!--notification end-->
				</div>
			</div>
</section></section></div>{% endif %}
<section id="main-content">
{% if  is_granted('ROLE_ADMIN') %}
	<section class="wrappera">{% else %} <section class="wrapper">{% endif %}
		<div class="table-agile-info">
   
   
   <div class="container">

  <div class="row">
    <div class="col-sm">   <h5>These are the recentely made Transactions</h5><br>
   {% for transaction in transactions %}
 
 <div class="card x">
  
  <div class="card-body">
    
<i class="fas fa-history fa-2x "></i>    <strong class="card-title"> Type: {{transaction.type}}   </strong>
    <p class="card-text">  Reference:{{transaction.product.reference}} </p>
    <p class="card-text">Quantity :{{transaction.quantity}}</p>
    <p class="card-text">Transaction Date:{{transaction.TransactionDate|date("m/d/Y") }}  </p> <br>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% if  is_granted('ROLE_ADMIN') %}
<a href="{{path('transaction_delete',{'id':transaction.id})}}" onclick="return confirm('Are you sure you want to delete this item?');"  >
<i class="fas fa-trash i fa-2x "></i></a></p>   {% endif %}
   
    
  </div>
</div>
<br> 
   {% endfor %}
    </div>{% if  is_granted('ROLE_ADMIN') %}
    <div class="col-sm">
    <h5>These are the Licences that needs to be extended soon</h5><br>
      {% for licence in licences %}
   
   
    <div class="card y">
  
  <div class="card-body">
    
<i class="fas fa-stamp fa-2x "></i>    <strong class="card-title">Licence Code code: {{licence.ProductName}}    </strong>
    <p class="card-text">  User:{{licence.Supplier}}</p>
    <p class="card-text">Category  :{{licence.category.name }}</p>
    <p class="card-text">Exiration Date :{{licence.ExpirationDate|date("m/d/Y") }}  </p> <br>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{path('licence_edit',{'id':licence.id})}}"  ><i class="i fas fa-edit fa-2x"></i></a>

    <a href="{{path('licence_delete',{'id':licence.id})}}" onclick="return confirm('Are you sure you want to delete this item?');"  >
<i class="fas fa-trash i fa-2x "></i></a></p>
   
    
  </div>
</div>
<br> 
   {% endfor %}
    </div>{% endif %}
    <div class="col-sm">
        <h5>These are the items that needs to be scanned</h5><br>
  {% for inventory in inventorys %}
    <div class="card z">
  
  <div class="card-body">
    
<i class="fas fa-box fa-2x "></i>    <strong class="card-title">Equipment code:{{inventory.Equipment}}  </strong>
    <p class="card-text"> Location:{{inventory.Locaation}}</p>
    <p class="card-text"> Purchase Date :{{inventory.PurchaseDate|date("m/d/Y") }}</p>
    <p class="card-text">Last Scan :{{inventory.LastScan|date("m/d/Y") }} </p> <br>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{path('inventory_edit',{'id':inventory.id})}}"  ><i class="i fas fa-edit fa-2x"></i></a>

    <a href="{{path('inventory_delete',{'id':inventory.id})}}" onclick="return confirm('Are you sure you want to delete this item?');"  >
<i class="fas fa-trash i fa-2x "></i></a></p>
   
    
  </div>
</div>
<br> 
   
   
   {% endfor %}
    </div>
      <div class="col-sm">
        <h5>These are the products running low on quantity</h5><br>
  {% for product in products %}
   <div class="card e">
  
  <div class="card-body">
    
<i class="fas fa-box-open fa-2x "></i>    <strong class="card-title">Reference : {{product.reference}}   </strong>
<!--    <p class="card-text">  Stocking Area:{{product.StockingArea}}</p>-->
    <p class="card-text">Manufacturer  :{{product.manufacturer}}</p>
    {% if product.quantity == 0 %}

    <p class="card-text" style="color:red;">Quantity: {{product.quantity}} </p> <br>
    {% else %}
    <p class="card-text">Quantity: {{product.quantity}} </p> <br>{% endif %}
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{path('product_edit',{'id':product.id})}}"  ><i class="fas fa-edit fa-2x"></i></a>

   </p>
   
    
  </div>
</div>
<br> 
   
   {% endfor %}
    </div>
  </div>
  
</div></div>
</div>
</section></section></div>

   {% endblock %}

templates/company/showInventory.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
a{color:black;}
th,h2,p,strong{color:#485785}
 @media print{

      body *{
        visibility: hidden;
      }
      .print-container, .print-container *{visibility: visible;}
    }
</style>
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
     <div class="container">
      <h2><i class="fas fa-info-circle"></i> Details about your Equipment : <strong>{{inventory.id}}</strong></h2>
  
    <br>
       <div class="card" style="width: 70rem;">
        <div class="card-body">
          <h3 class="card-title print-container"><strong> Equipment:   {{ inventory.equipment  }}</strong></h3>
            <br>
        <div class="row print-container">
    <div class="form-group col">
    <label for="firstname" class="form-label"><i class="fas fa-user"></i><strong> User:</strong> {{ inventory.user }}</label> 
   <hr>    </div> 
 <div class="form-group col">
     <label for="prenom" class="form-label"> <i class="fas fa-cog"></i><strong> OperatingSystem:</strong> {{ inventory.operatingsystem}}  </label> 
    <hr>  </div> 
    
    
    
 </div>
    <div class="row print-container">
    <div class="form-group col">
    <label for="firstname" class="form-label"><i class="fas fa-star"></i><strong> State:</strong> {{ inventory.state }} </label> 
     <hr>  </div> 
 <div class="form-group col">
     <label for="prenom" class="form-label"><i class="fas fa-location-arrow"></i><strong> Location:</strong> {{ inventory.locaation }}    </label> 
    <hr>  </div> 
    
    
    
 </div>
 
    <div class="row print-container">
    <div class="form-group col">
    <label for="firstname" class="form-label">    <i class="fas fa-copyright"></i><strong> Brand:</strong> {{ inventory.brand }}</label> 
     <hr>  </div> 
 <div class="form-group col">
     <label for="prenom" class="form-label">  <i class="fas fa-sort-numeric-up"></i><strong> Model :</strong> {{ inventory.model }} </label> 
     <hr> </div> 
    
    
    
 </div>
   <div class="row print-container">
    <div class="form-group col">
    <label for="firstname" class="form-label">      <i class="fas fa-barcode"></i><strong> LastScan :</strong> {{ inventory.lastscan|date("m/d/Y") }}</label> 
     <hr>  </div> 
 <div class="form-group col print-container">
     <label for="prenom" class="form-label"><i class="fas fa-wrench"></i><strong> Lastmaintenance :</strong> {{ inventory.lastmaintenance|date("m/d/Y") }}  </label> 
   <hr>   </div> 
    
    
    
 </div>
    <div class="row print-container">
    <div class="form-group col print-container">
    <label for="firstname" class="form-label">    <i class="fas fa-parachute-box"></i><strong> supplier :</strong> {{ inventory.supplier }}</label> 
      <hr> </div> 
   <div class="form-group col print-container">
    <label for="firstname" class="form-label">     <i class="fas fa-shopping-cart"></i><strong> Purchasedate :</strong> {{ inventory.purchasedate |date("m/d/Y")}}</label> 
      <hr> </div> 
 
    
    
    
    
 </div>
 
         
            <a href="{{path('inventory_edit',{'id':inventory.id})}}" class="btn btn-warning" title="" >
                <i class="fas fa-edit"></i>
            </a>
            <a href="{{path('inventory_delete',{'id':inventory.id})}}" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger" title=""
                 ><i class="fas fa-trash-alt"></i></a>
                            
 <a  class="btn btn-info" title="" onclick="window.print();" >
  
                <i class="fas fa-print"></i>
                
            </a>
                 </div>
      </div>
     <br><br>
   
</div>
</section></section></div>
{% endblock %}
{% block javascripts %}
<script src="{{ asset('js/main.js') }}"></script>
<script>
function myFunction() {
  alert("Equipment is Now being deleted");
}
</script>
<script>
    function printPage() {
      window.print();
    }
    </script>

{% endblock %}

templates/company/showLicence.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
a{color:black;}
th,h2,p,strong{color:#485785}
</style>
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
     <div class="container"> <h2><i class="fas fa-info-circle"></i> Details about your Licence : <strong></strong></h2>
  <br>
     <div class="card text-center">
    
  <div class="card-header panel-heading">
   <strong> Licence   {{licence.id}}</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong>Name: </strong> {{licence.ProductName}}</h5>
    <p class="card-title"><strong>User:</strong> {{licence.User}}</p>
    <p class="card-title"><strong>Supplier:</strong> {{licence.supplier}}</p>
    <p class="card-text"><strong>Compilance Type: {{licence.CompilanceType}}</strong></p>
       <p class="card-text"><strong>Categorie: {{licence.category.name}}</strong></p>
    <p class="card-text"><strong>Purchase Date:</strong> {{licence.PurchaseDate|date("m/d/Y")}}</p>
    <p class="card-text"><strong>Expiration  Date:</strong> {{licence.ExpirationDate|date("m/d/Y")}}</p>
       <p class="card-text"><strong>Category Description:</strong> {{licence.category.description}}</p>
    </div>
  <div class="card-footer text-muted">
  <a href="{{path('licence_edit',{'id':licence.id})}}" class="btn btn-warning" title="" >
                <i class="fas fa-edit"></i>
            </a>
            <a href="{{path('licence_delete',{'id':licence.id})}}" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger" title=""
                 ><i class="fas fa-trash-alt"></i></a>
 
  </div>
</div>
   
           
     
   
</div>

</section></section></div>  <br>  <br>  <br>  <br>  <br>
{% endblock %}